name: C/C++ CI

on:
  push:
    branches: [ "BlackCLK_ex_2" ]
  pull_request:
    branches: [ "BlackCLK_ex_2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CI Build
      run: chmod +x ci-build.sh && ./ci-build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: cLK (bin)
        path: ./build-htcleo/lk.bin
    - uses: actions/upload-artifact@v3
      with:
        name: cLK (LEOIMG.nbh)
        path: ./build-htcleo/LEOIMG.nbh
